DROP TABLE IF EXISTS athletics;
DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS admins;
DROP TABLE IF EXISTS partners;
DROP TABLE IF EXISTS users;


CREATE TABLE users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(30) NOT NULL UNIQUE ,
    email varchar(50) NOT NULL UNIQUE ,
    password varchar(60) NOT NULL ,
    role varchar(30) NOT NULL ,
    first_name varchar(30) NOT NULL ,
    last_name varchar(30) NOT NULL ,
    father_name varchar(30),
    date_of_birth date CHECK (date_of_birth > '1900-01-01') NOT NULL,
    number varchar(20) NOT NULL,
    address varchar NOT NULL ,
    have_education boolean NOT NULL default false,
    education varchar,
    telegram_link varchar(40),
    vkontakte_link varchar(40),
    description varchar
);

CREATE TABLE athletics (
    user_id int PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    education varchar,
    grade smallint
);

CREATE TABLE members (
    user_id int PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    federation_name varchar NOT NULL UNIQUE ,
    work_position varchar(100) NOT NULL,
    approved boolean NOT NULL default false
);

CREATE TABLE admins (
    user_id int PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    approved boolean NOT NULL default false
);

CREATE TABLE partners (
    user_id int PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    organization_name varchar NOT NULL UNIQUE ,
    approved boolean NOT NULL default false

);

INSERT INTO users(login, email, password, role, first_name, last_name, father_name, date_of_birth, number, address, have_education, education, telegram_link, vkontakte_link, description) VALUES
('athletic1', 'Ivan15@gmail.com', '12345', 'ATHLETIC', 'Ivan', 'Petrov', 'Ivanovich', '2000-01-01', '+79281112233', 'Russia, Moscow, Arbat street, 43', false, null, 'ivan15', null, 'Athletic from Moscow'),
('athletic2', 'Igor10@gmail.com', '12345', 'ATHLETIC', 'Igor', 'Ivanov', null, '2000-04-01', '+79285552233', 'Russia, Saint Peterburg, Naberezhaya, 40', true, 'SPSU', 'igor10', null, 'Athletic from St P');

INSERT INTO athletics(user_id, education, grade) VALUES
(1, 'MSU', '3'),
(2, null, null);
